repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: ['--unsafe']
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: {{cookiecutter.uv_version}}
    hooks:
      - id: uv-lock
        args: ["--locked"]

  - repo: https://github.com/psf/black
    rev: "24.10.0"
    hooks:
      - id: black
        args:
          - --preview

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.8.0"
    hooks:
      - id: ruff
        args: [--exit-non-zero-on-fix]
      - id: ruff-format

{%- if cookiecutter.mkdocs == 'y' %}

  - repo: https://github.com/PyCQA/docformatter
    rev: "v1.7.5"
    hooks:
      - id: docformatter
        additional_dependencies: [tomli]
        args: [--in-place, --config, ./pyproject.toml]
{%- endif %}

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks
