coverage:
  range: 70..100
  round: down
  precision: 2
  status: # Ref: https://docs.codecov.com/docs/commit-status
    patch: off # Disable patch status
    project:
      default:
        target: auto  # use the coverage from the base commit (pull request base or parent commit) coverage to compare against
        threshold: 5%
comment:
  layout: " diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: false        # [true :: must have a base report to post]
  require_head: true       # [true :: must have a head report to post]
  hide_project_coverage: false # [true :: only show coverage on the git diff]
